import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

const Be = Be_Vietnam_Pro({
  subsets:['latin'],
  weight:['300','800','400','600']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Be.className} antialiased bg-[#20293A] `}
      >
        {children}
      </body>
    </html>
  );
}
